# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#créations des users
require 'faker'
#cities
c1=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c2=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c3=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c4=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c5=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c6=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c7=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c8=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c9=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
c10=City.create(name: Faker::Lorem.words(number: 2).join,zip_code: Faker::String.random(length: 8))
u1=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example1@example.com",age: Faker::Number.between(from: 1, to: 99),city: c1)
u2=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example2@example.com",age: Faker::Number.between(from: 1, to: 99),city: c2)
u3=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example3@example.com",age: Faker::Number.between(from: 1, to: 99),city: c3)
u4=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example4@example.com",age: Faker::Number.between(from: 1, to: 99),city: c4)
u5=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example5@example.com",age: Faker::Number.between(from: 1, to: 99),city: c5)
u6=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example6@example.com",age: Faker::Number.between(from: 1, to: 99),city: c6)
u7=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example7@example.com",age: Faker::Number.between(from: 1, to: 99),city: c7)
u8=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example8@example.com",age: Faker::Number.between(from: 1, to: 99),city: c8)
u9=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example9@example.com",age: Faker::Number.between(from: 1, to: 99),city: c9)
u10=User.create(first_name: Faker::Name.first_name,last_name: Faker::Name.last_name,email:"example10@example.com",age: Faker::Number.between(from: 1, to: 99),city: c10)
g1=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g2=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g3=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g4=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u3)
g5=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u6)
g6=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u4)
g7=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g8=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g9=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g10=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g11=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u5)
g12=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u2)
g13=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u2)
g14=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
g15=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u3)
g16=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u7)
g17=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u6)
g18=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u10)
g19=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u8)
g20=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u9)
gt1=Gossip.create(title: Faker::Lorem.words(number: 1),content: Faker::Lorem.words(number: 10).join(" "),user:u1)
t1=Tag.create(title: Faker::Lorem.words(number: 1))
t2=Tag.create(title: Faker::Lorem.words(number: 1))
t3=Tag.create(title: Faker::Lorem.words(number: 1))
t4=Tag.create(title: Faker::Lorem.words(number: 1))
t5=Tag.create(title: Faker::Lorem.words(number: 1))
t6=Tag.create(title: Faker::Lorem.words(number: 1))
t7=Tag.create(title: Faker::Lorem.words(number: 1))
t8=Tag.create(title: Faker::Lorem.words(number: 1))
t9=Tag.create(title: Faker::Lorem.words(number: 1))
t10=Tag.create(title: Faker::Lorem.words(number: 1))
gt2=GossipTagAttribution.create(gossip: g1 , tag: t1)
gt3=GossipTagAttribution.create(gossip: g7 , tag: t2)
gt4=GossipTagAttribution.create(gossip: g1 , tag: t1)
gt5=GossipTagAttribution.create(gossip: g11 , tag: t1)
gt6=GossipTagAttribution.create(gossip: g10 , tag: t3)
gt7=GossipTagAttribution.create(gossip: g2 , tag: t1)
gt8=GossipTagAttribution.create(gossip: g5 , tag: t4)
gt9=GossipTagAttribution.create(gossip: g1 , tag: t5)
gt10=GossipTagAttribution.create(gossip: g2 , tag: t1)
gt11=GossipTagAttribution.create(gossip: g1 , tag: t7)
gt12=GossipTagAttribution.create(gossip: g7 , tag: t6)
gt13=GossipTagAttribution.create(gossip: g3 , tag: t1)
gt14=GossipTagAttribution.create(gossip: g1 , tag: t4)
gt15=GossipTagAttribution.create(gossip: g14 , tag: t8)
gt16=GossipTagAttribution.create(gossip: g1 , tag: t9)
gt17=GossipTagAttribution.create(gossip: g15 , tag: t1)
gt18=GossipTagAttribution.create(gossip: g11 , tag: t8)
gt19=GossipTagAttribution.create(gossip: g8 , tag: t3)
gt20=GossipTagAttribution.create(gossip: g1 , tag: t2)
